version: '3'

services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
      - "9000"
    links:
      - postgres:postgres
    volumes:
      - ./web:/app/web
    env_file: env.config
    environment:
      DEBUG: 'True'
    # command: /usr/local/bin/gunicorn nfe.wsgi:application -w 2 -b :8000
    command: python manage.py runserver 0.0.0.0:8000

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    links:
      - web:web

  postgres:
    restart: always
    image: postgres:11.5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
