version: '3'

services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    links:
      - postgres:postgres
    volumes:
      - ./web:/app/web
      - ./web/staticfiles:/staticfiles
    env_file: env.config
    environment:
      DEBUG: 'True'
    command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate && /usr/local/bin/gunicorn nfe.wsgi:application -w 2 -b :8000"
    #command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - ./web/staticfiles:/staticfiles
    links:
      - web:web

  postgres:
    restart: always
    image: postgres:11.5
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
