# Generated by Django 2.2.4 on 2019-08-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nfe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_key', models.CharField(max_length=44, unique=True, verbose_name='Access Key')),
                ('xml', models.CharField(max_length=4000, verbose_name='XML')),
                ('value', models.CharField(blank=True, max_length=20, null=True, verbose_name='Value')),
            ],
        ),
    ]
