# Generated by Django 2.2.4 on 2019-08-24 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190824_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nfe',
            old_name='updated_at',
            new_name='update_at',
        ),
    ]
